window.addEventListener('message',e=>{const d=e.data;if(!d||typeof d!=='object')return;if(d.type==='sonam-image'&&typeof d.image==='string'){localStorage.setItem('sonamGeneratedImage',d.image);location.href='auth.html?mode=sonam'}if(d.type==='sonam-session'){localStorage.setItem('sonamSession',JSON.stringify(d.user||{}));document.getElementById('sonamOption').hidden=false}});
(function(){
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)], params=new URLSearchParams(location.search), mode=params.get('mode');
const tabs=qa('.tab'), forms={signin:q('#signinForm'),signup:q('#signupForm')};
function openTab(name){tabs.forEach(b=>b.classList.toggle('active',b.dataset.tab===name));Object.entries(forms).forEach(([k,v])=>v.classList.toggle('active',k===name));}
tabs.forEach(b=>b.addEventListener('click',()=>openTab(b.dataset.tab)));
qa('.toggle-password').forEach(b=>b.addEventListener('click',()=>{const input=q('#'+b.dataset.target);input.type=input.type==='password'?'text':'password';b.innerHTML=input.type==='password'?'<i class="fa-solid fa-eye"></i>':'<i class="fa-solid fa-eye-slash"></i>'}));
const sonamImage=localStorage.getItem('sonamGeneratedImage')||params.get('image');
if(sonamImage){localStorage.setItem('sonamGeneratedImage',sonamImage)}
if(mode==='sonam'||sonamImage){q('#sonamOption').hidden=false;q('#authEyebrow').textContent='SONAM IMAGE READY';q('#authTitle').textContent='Continue your creation.';q('#authSubtitle').textContent='Use your Sonam session or choose another way to enter ASTRA.'}
function enter(kind){localStorage.setItem('astraSession',JSON.stringify({type:kind,name:kind==='sonam'?'Sonam User':'Guest',time:Date.now()}));location.href='photo-editor.html'+(kind==='sonam'?'?mode=sonam':'')}
q('#continueSonam').addEventListener('click',()=>enter('sonam'));
q('#continueGuest').addEventListener('click',()=>enter('guest'));
forms.signin.addEventListener('submit',e=>{e.preventDefault();const identity=q('#signinIdentity').value.trim(),password=q('#signinPassword').value;if(identity.length<3||password.length<4){q('#signinMessage').textContent='Enter a valid email or mobile and password.';return}const users=JSON.parse(localStorage.getItem('astraUsers')||'[]');const user=users.find(u=>(u.email===identity||u.mobile===identity)&&u.password===password);if(!user){q('#signinMessage').textContent='Account not found or password is incorrect.';return}localStorage.setItem('astraSession',JSON.stringify({type:'account',name:user.name,email:user.email,time:Date.now()}));location.href='photo-editor.html'});
forms.signup.addEventListener('submit',e=>{e.preventDefault();const name=q('#signupName').value.trim(),email=q('#signupEmail').value.trim().toLowerCase(),mobile=q('#signupMobile').value.replace(/\D/g,''),password=q('#signupPassword').value,confirm=q('#signupConfirm').value,msg=q('#signupMessage');if(name.length<2||!/^\S+@\S+\.\S+$/.test(email)||mobile.length<10||password.length<6){msg.textContent='Fill all fields correctly. Password must be at least 6 characters.';return}if(password!==confirm){msg.textContent='Passwords do not match.';return}const users=JSON.parse(localStorage.getItem('astraUsers')||'[]');if(users.some(u=>u.email===email||u.mobile===mobile)){msg.textContent='An account with this email or mobile already exists.';return}users.push({name,email,mobile,password});localStorage.setItem('astraUsers',JSON.stringify(users));localStorage.setItem('astraSession',JSON.stringify({type:'account',name,email,time:Date.now()}));location.href='photo-editor.html'});
})();
