(function(){
function init(){
if(typeof fabric==='undefined'){ASTRA.toast('Fabric.js could not be loaded. Check your internet connection.');return}
const c=new fabric.Canvas('editorCanvas',{preserveObjectStacking:true,selection:true});ASTRA.state.canvas=c;c.backgroundColor='#101827';c.renderAll();
const session=JSON.parse(localStorage.getItem('astraSession')||'null');document.getElementById('sessionLabel').textContent=session?`${session.name||'Guest'} mode`:'Guest mode';
ASTRA.state.pages=[{name:'Page 1',json:c.toJSON(['name','id','dataType','isBackground'])}];ASTRA.state.pageIndex=0;
ASTRA.updateHistoryButtons=()=>{document.getElementById('undoBtn').disabled=ASTRA.state.historyIndex<=0;document.getElementById('redoBtn').disabled=ASTRA.state.historyIndex>=ASTRA.state.history.length-1};
ASTRA.saveHistory();
const bind=(id,event,fn)=>document.getElementById(id)?.addEventListener(event,fn);
const bindInput=(id,fn)=>bind(id,'input',fn);
ASTRA.setTool('select');
ASTRA.smartGuides();
function updateRange(id,valueId,suffix=''){const input=document.getElementById(id),out=document.getElementById(valueId);if(input&&out)out.textContent=input.value+suffix}
['brightness','contrast','saturation','blur'].forEach(id=>bindInput(id,()=>{updateRange(id,id+'Value');ASTRA.applyFilters()}));
[['imageOpacity','imageOpacityValue','%'],['imageRotation','imageRotationValue','°'],['objectOpacity','objectOpacityValue','%'],['objectRotation','objectRotationValue','°'],['fontSize','fontSizeValue',''],['shapeStrokeWidth','shapeStrokeWidthValue',''],['gradientAngle','gradientAngleValue','°'],['shadowBlur','shadowBlurValue',''],['shadowOffsetX','shadowOffsetXValue',''],['shadowOffsetY','shadowOffsetYValue',''],['glowBlur','glowBlurValue',''],['brushSize','brushSizeValue',''],['penWidth','penWidthValue',''],['frameWidth','frameWidthValue',''],['frameOpacity','frameOpacityValue','%']].forEach(([id,out,s])=>bindInput(id,()=>{updateRange(id,out,s);applyLive(id)}));
function applyLive(id){const o=ASTRA.active();if(!o)return;if(id==='objectOpacity'||id==='imageOpacity')o.set('opacity',Number(document.getElementById(id).value)/100);if(id==='objectRotation'||id==='imageRotation')o.set('angle',Number(document.getElementById(id).value));if(id==='fontSize'&&['i-text','textbox','text'].includes(o.type))o.set('fontSize',Number(document.getElementById(id).value));if(id==='fontFamily'&&['i-text','textbox','text'].includes(o.type))o.set('fontFamily',document.getElementById(id).value);if(id==='fontColor'&&['i-text','textbox','text'].includes(o.type))o.set('fill',document.getElementById(id).value);if(id==='textAlign'&&['i-text','textbox','text'].includes(o.type))o.set('textAlign',document.getElementById(id).value);if(id==='shapeFill'&&o.type!=='image')o.set('fill',document.getElementById(id).value);if(id==='shapeStroke')o.set('stroke',document.getElementById(id).value);if(id==='shapeStrokeWidth')o.set('strokeWidth',Number(document.getElementById(id).value));if(id==='brushSize'&&c.isDrawingMode&&c.freeDrawingBrush)c.freeDrawingBrush.width=Number(document.getElementById(id).value);if(id==='brushColor'&&c.isDrawingMode&&c.freeDrawingBrush)c.freeDrawingBrush.color=document.getElementById(id).value;if(id==='penColor'&&ASTRA.state.pen)ASTRA.state.pen.color=document.getElementById(id).value;if(id==='penWidth'&&ASTRA.state.pen)ASTRA.state.pen.width=Number(document.getElementById(id).value);c.requestRenderAll();ASTRA.markDirty()}
['fontFamily','fontColor','textAlign','shapeFill','shapeStroke','shapeStrokeWidth','objectOpacity','objectRotation','imageOpacity','imageRotation'].forEach(id=>bindInput(id,()=>applyLive(id)));
bind('boldBtn','click',()=>{const o=ASTRA.active();if(!o||!['i-text','textbox','text'].includes(o.type))return;const active=o.fontWeight==='700'||o.fontWeight==='bold';o.set('fontWeight',active?'400':'700');ASTRA.markDirty();ASTRA.updateSelection();c.requestRenderAll()});
bind('italicBtn','click',()=>{const o=ASTRA.active();if(!o||!['i-text','textbox','text'].includes(o.type))return;o.set('fontStyle',o.fontStyle==='italic'?'normal':'italic');ASTRA.markDirty();ASTRA.updateSelection();c.requestRenderAll()});
bind('underlineBtn','click',()=>{const o=ASTRA.active();if(!o||!['i-text','textbox','text'].includes(o.type))return;o.set('underline',!o.underline);ASTRA.markDirty();ASTRA.updateSelection();c.requestRenderAll()});
bind('uploadImage','click',()=>{document.getElementById('imageInput').dataset.replace='0';document.getElementById('imageInput').click()});bind('replaceImage','click',()=>{document.getElementById('imageInput').dataset.replace='1';document.getElementById('imageInput').click()});bind('replaceSelectedImage','click',()=>{document.getElementById('imageInput').dataset.replace='1';document.getElementById('imageInput').click()});bind('imageInput','change',e=>{ASTRA.openImageFile(e.target.files[0],e.target.dataset.replace==='1');e.target.value=''});
bind('duplicateImage','click',ASTRA.duplicate);bind('deleteImage','click',ASTRA.deleteActive);bind('duplicateBtn','click',ASTRA.duplicate);bind('deleteBtn','click',ASTRA.deleteActive);bind('layerFront','click',ASTRA.bringFront);bind('layerBack','click',ASTRA.sendBack);
bind('addHeading','click',()=>{ASTRA.setTool('text');ASTRA.addText('heading')});bind('addParagraph','click',()=>{ASTRA.setTool('text');ASTRA.addText('paragraph')});const shapeButtons={rectangle:'addRectangle',rounded:'addRoundedRect',circle:'addCircle',triangle:'addTriangle',star:'addStar',arrow:'addArrow',line:'addLine'};Object.entries(shapeButtons).forEach(([type,id])=>bind(id,'click',()=>{ASTRA.setTool('shapes');ASTRA.addShape(type)}));
bind('gradientTool','click',()=>ASTRA.setTool('gradient'));bind('applyGradient','click',ASTRA.applyGradient);bind('shadowTool','click',()=>ASTRA.setTool('shadow'));bind('applyShadow','click',ASTRA.applyShadow);bind('removeShadow','click',ASTRA.removeShadow);bind('glowTool','click',()=>ASTRA.setTool('glow'));bind('applyGlow','click',ASTRA.applyGlow);bind('removeGlow','click',ASTRA.removeGlow);bind('filtersTool','click',()=>ASTRA.setTool('filters'));bind('resetFilters','click',ASTRA.resetFilters);
bind('brushTool','click',()=>{ASTRA.setTool('brush');ASTRA.setBrushMode(true)});bind('disableBrush','click',()=>ASTRA.setBrushMode(false));bind('penTool','click',ASTRA.setPenMode);bind('finishPen','click',ASTRA.finishPen);bind('finishPenProperty','click',ASTRA.finishPen);bind('cropTool','click',()=>{ASTRA.setTool('crop');ASTRA.startCrop()});bind('applyCrop','click',ASTRA.applyCrop);bind('cancelCrop','click',ASTRA.cancelCrop);bind('frameTool','click',()=>ASTRA.setTool('frame'));document.querySelectorAll('.frame-btn').forEach(b=>b.addEventListener('click',()=>ASTRA.applyFrame(b.dataset.frame)));bind('eyedropperTool','click',ASTRA.startEyedropper);
bind('templatesTool','click',()=>ASTRA.setTool('templates'));document.querySelectorAll('[data-template]').forEach(b=>b.addEventListener('click',()=>ASTRA.applyTemplate(b.dataset.template)));bind('pagesTool','click',()=>{ASTRA.setTool('pages');ASTRA.updatePagesUI?.()});bind('addPage','click',ASTRA.addPage);bind('duplicatePage','click',ASTRA.duplicatePage);bind('deletePage','click',ASTRA.deletePage);bind('renamePage','click',ASTRA.renamePage);bind('previousPage','click',()=>{if(ASTRA.state.pageIndex>0)ASTRA.loadPage(ASTRA.state.pageIndex-1)});bind('nextPage','click',()=>{if(ASTRA.state.pageIndex<ASTRA.state.pages.length-1)ASTRA.loadPage(ASTRA.state.pageIndex+1)});
bind('aiTool','click',()=>ASTRA.setTool('ai'));document.querySelectorAll('.ai-action').forEach(b=>b.addEventListener('click',()=>ASTRA.aiAction(b.dataset.ai)));bind('aiGenerateBtn','click',()=>{const p=document.getElementById('aiPrompt').value.trim().toLowerCase();if(!p)return ASTRA.toast('Describe an edit first');if(p.includes('gray')||p.includes('black and white'))ASTRA.aiAction('grayscale');else if(p.includes('enhance')||p.includes('improve'))ASTRA.aiAction('enhance');else if(p.includes('color'))ASTRA.aiAction('auto-color');else ASTRA.toast('Prompt applied as a local editing action')});
bind('saveProject','click',ASTRA.saveProject);bind('saveBtn','click',ASTRA.saveProject);bind('openProject','click',()=>document.getElementById('projectFile').click());bind('projectFile','change',e=>{ASTRA.openProjectFile(e.target.files[0]);e.target.value=''});bind('printCanvas','click',()=>{const data=c.toDataURL({format:'png',multiplier:1});const w=window.open('','_blank','width=1100,height=800');if(w){w.document.write('<html><head><title>ASTRA Print</title><style>html,body{margin:0;background:#fff;height:100%;display:grid;place-items:center}img{max-width:96%;max-height:96%;object-fit:contain}</style></head><body><img src="'+data+'"></body></html>');w.document.close();w.focus();setTimeout(()=>w.print(),300)}});bind('exportPNG','click',()=>ASTRA.exportImage('png'));bind('exportJPG','click',()=>ASTRA.exportImage('jpg'));bind('exportPDF','click',ASTRA.exportPDF);bind('exportBtn','click',()=>document.getElementById('exportMenu').classList.toggle('open'));document.querySelectorAll('[data-export]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.export;if(type==='pdf')ASTRA.exportPDF();else ASTRA.exportImage(type);document.getElementById('exportMenu').classList.remove('open')}));document.addEventListener('click',e=>{if(!e.target.closest('.export-wrap'))document.getElementById('exportMenu')?.classList.remove('open')});
bind('undoBtn','click',ASTRA.undo);bind('redoBtn','click',ASTRA.redo);bind('zoomInBtn','click',()=>{const z=Math.min(4,c.getZoom()+.1);c.setZoom(z);ASTRA.state.zoom=z;document.getElementById('zoomValue').textContent=Math.round(z*100)+'%'});bind('zoomOutBtn','click',()=>{const z=Math.max(.2,c.getZoom()-.1);c.setZoom(z);ASTRA.state.zoom=z;document.getElementById('zoomValue').textContent=Math.round(z*100)+'%'});bind('fitCanvas',ASTRA.fitCanvas);bind('toggleGrid',()=>{ASTRA.state.grid=!ASTRA.state.grid;document.getElementById('gridOverlay').classList.toggle('visible',ASTRA.state.grid)});
bind('setBackground',()=>document.getElementById('backgroundColor').click());bind('applyBackground',()=>{c.backgroundColor=document.getElementById('backgroundColor').value;c.renderAll();ASTRA.markDirty()});bindInput('backgroundColor',()=>{c.backgroundColor=document.getElementById('backgroundColor').value;c.renderAll();ASTRA.markDirty()});bind('clearProperties',()=>{c.discardActiveObject();ASTRA.updateSelection();c.requestRenderAll();if(window.innerWidth<=820)document.getElementById('propertiesPanel').classList.remove('open')});
bind('flipHorizontal',()=>{const o=ASTRA.active();if(!o)return ASTRA.toast('Select an image first');o.set('flipX',!o.flipX);ASTRA.markDirty();c.requestRenderAll()});bind('flipVertical',()=>{const o=ASTRA.active();if(!o)return ASTRA.toast('Select an image first');o.set('flipY',!o.flipY);ASTRA.markDirty();c.requestRenderAll()});bind('removeBackgroundProperty',()=>ASTRA.aiAction('remove-background'));
c.on('selection:created',ASTRA.updateSelection);c.on('selection:updated',ASTRA.updateSelection);c.on('selection:cleared',ASTRA.updateSelection);c.on('object:modified',()=>{ASTRA.saveHistory();ASTRA.updateSelection()});c.on('object:added',()=>{if(!ASTRA.restoring)ASTRA.saveHistory();document.getElementById('emptyCanvas').classList.toggle('hidden',c.getObjects().some(o=>!o.isBackground))});c.on('object:removed',()=>{if(!ASTRA.restoring)ASTRA.saveHistory();document.getElementById('emptyCanvas').classList.toggle('hidden',c.getObjects().some(o=>!o.isBackground))});c.on('path:created',()=>{ASTRA.saveHistory();ASTRA.updateSelection()});c.on('mouse:down',opt=>{if(ASTRA.state.tool==='eyedropper'){ASTRA.pickColor(opt.pointer);return}if(ASTRA.state.tool==='pen'&&ASTRA.state.pen){ASTRA.state.pen.points.push({x:opt.pointer.x,y:opt.pointer.y});const dot=new fabric.Circle({left:opt.pointer.x,top:opt.pointer.y,radius:3,fill:ASTRA.state.pen.color,selectable:false,evented:false,name:'Pen guide'});c.add(dot)}});
window.addEventListener('resize',()=>ASTRA.fitCanvas());
ASTRA.fitCanvas();ASTRA.updateSelection();window.dispatchEvent(new Event('astra:ready'));setTimeout(()=>ASTRA.fitCanvas(),120);if(new URLSearchParams(location.search).get('mode')!=='sonam')ASTRA.restoreAutosave?.();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
